name: Build and Publish image to Docker Hub
on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build image
      run: | 
        docker build ./backend-api/ -t 4ndsilva/home-care-api:latest
    - name: push image to docker hub
      run: |
        docker push docker push 4ndsilva/home-care-backend-api:latest
