name: Build and Publish image to Docker Hub
on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: OWASP Dependency-Check
      uses: dependency-check/dependency-check-action@v2
      with:
        project: 'home-care-backend-api'
        scan: './backend/'
        
    - name: build image
      run: | 
        docker build ./backend/ -t 4ndsilva/home-care-backend-api:latest
        
    - name: push image to docker hub
      run: |
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u 4ndsilva --password-stdin
        docker push 4ndsilva/home-care-backend-api:latest
